### ISSUE TITLE
Update Scraping Logic for Co-Authored Page

### ISSUE THREAD

**Issue by maffiemd** [MaffieLab/Coauthor#58]
### Problem: 

Existing implementation does not capture manuscripts that are co-authored if there is another co-authored paper currently under review. This is because Manuscript Central divides lead-authored papers into two pages ("Manuscripts Under Review" and "Manuscripts with Decisions") but pools those categories for papers where the user is not the lead author. As a result, the Author Table includes both papers with decisions and those awaiting decision. This breaks the scarping logic because the current implementation assumes all manuscripts have decisions. As most papers are co-authored, this poses a significant coverage problem for the project.

### Proposed solution:

1. Update scraping logic to fire on the "Manuscripts I have Co-Authored Page"
2. Scape all manuscripts, even those under review, into the GlobalStore
3. Filter the GlobalStore into a new variable, ManuscriptsWithDecsiions that removes manuscripts under review. Pass this object to the sendData function to transmit those manuscripts to the server
4. Update the UI logic as follows:
- for manuscripts under review, use today's date as a decision date so authors can see how long their paper has been under review. 
- change the render function to only display a green check mark if the paper has been uploaded to the server. Otherwise, display a red X.

**Comment by leonzh2k** [comment]
@maffiemd The proposed solution sounds good. I feel like just displaying a red X isn't very good for UX because it might make the user think that the manuscript was supposed to be uploaded, but something went wrong. We should make it clear that the extension does not accept manuscripts without decisions. Indicate that 1: the manuscript wasn't uploaded, and 2: _why_ it wasn't uploaded. It will be hard to convey both in an image, so maybe we should simply put a text reading "No: unknown decision" or something like that.
